language: php
php:
  - '5.5'
  - '5.6'
  - '7.0'
sudo: false

env:
  - TYPO3_VERSION="7.*"
  - TYPO3_VERSION="8.*"

matrix:
  exclude:
    - env: TYPO3_VERSION="8.*"
      php: '5.5'
    - env: TYPO3_VERSION="8.*"
      php: '5.6'

before_script:
  - composer require typo3/cms:${TYPO3_VERSION}
  - composer require friendsofphp/php-cs-fixer

script:
  - composer run checkstyle-fix
