<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "ttcontent_to_txnews"
 *
 * Auto generated by Extension Builder 2014-08-31
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'tt_content to tx_news converter',
    'description' => 'tt_content to tx_news converter',
    'category' => 'plugin',
    'author' => 'Cedric Ziel',
    'author_email' => 'cedric@cedric-ziel.com',
    'state' => 'alpha',
    'internal' => '',
    'uploadfolder' => '0',
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '',
    'constraints' => [
        'depends' => [
            'typo3' => '6.2',
        ],
        'conflicts' => [
        ],
        'suggests' => [
        ],
    ],
];
